image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.1
stages:
  - package
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: package
  script:
    - node_module agile
    - node_build linux_build
    - cd $CI_PROJECT_DIR
    - kaniko -c $CI_PROJECT_DIR -f $CI_PROJECT_DIR/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}

release:
  stage: release
  script:
    - chart_build

.auto_devops: &auto_devops |
    http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"`
    if [ "$http_status_code" != "200" ]; then
      cat .auto_devops.sh
      exit 1
    fi
    source .auto_devops.sh    
    function node_module(){
        cd ${1}
        npm install -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
        cd ..
        python ./${1}/node_modules/choerodon-front-boot/structure/menu/__init__.py -o yml -m ${1}
        python ./${1}/node_modules/choerodon-front-boot/structure/dashboard/__init__.py -o yml -m ${1}
        cd ${1}
    }

    function node_build(){
        chmod -R 777 node_modules
        npm run ${1:-"build"} -registry https://nexus.choerodon.com.cn/repository/choerodon-npm/  --sass-binary-site=http://npm.taobao.org/mirrors/node-sass --loglevel verbose
        find dist -name '*.js' | xargs sed -i "s/localhost:version/$CI_COMMIT_TAG/g"
    }

before_script:
  - *auto_devops
